PMM-7 refactoring
percona/pmm-infra pull request #21
Opened 2022-04-22 13:48 UTC by nikita-b

2022-04-24 14:47 UTC, atymchuk requested changes

2022-04-24 14:47 UTC, atymchuk commented on packer/ansible/agent.yml
> +          - https://rpm.nodesource.com/pub_14.x/el/7/{{ ansible_architecture }}/nodejs-{{ node_version }}-1nodesource.{{ ansible_architecture }}.rpm
I looks we already use NodeJS v16 - https://github.com/Percona-Lab/pmm-submodules/blob/b79a9d61a56c55d4ac6fbd1261bb6837e13d2942/build/rpmbuild-docker/Dockerfile#L4

2022-04-24 14:47 UTC, atymchuk commented on packer/ansible/agent.yml
> +          - https://rpm.nodesource.com/pub_14.x/el/7/{{ ansible_architecture }}/nodejs-{{ node_version }}-1nodesource.{{ ansible_architecture }}.rpm
https://github.com/percona-platform/saas-ui/blob/main/package.json#L117

2022-04-24 14:47 UTC, atymchuk commented on packer/ansible/agent.yml
> +    - name: pull and cache docker images
```suggestion
    - name: Pull and cache docker images
```

2022-04-24 14:47 UTC, atymchuk commented on packer/ansible/agent.yml
> +      loop:
Just one item, do we need to loop?

2022-04-25 10:21 UTC, nikita-b commented on packer/ansible/agent.yml
> +      loop:
Yes, I plan to add more images :)

2022-05-04 14:44 UTC, atymchuk requested changes

2022-05-04 14:44 UTC, atymchuk commented on packer/ansible/agent.yml
> +    - name: Install NodeJS
```suggestion
    - name: Install some software
```

2022-05-05 09:49 UTC, atymchuk approved these changes

2022-05-05 09:49 UTC, merged